######################################################################
# Automatically generated by qmake (3.0) ?? 9? 1 20:29:34 2017
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = adder3
INCLUDEPATH += .

# Input
HEADERS += adder.h jfq.h
SOURCES += adder.cpp testadder.cpp
