######################################################################
# Automatically generated by qmake (3.0) ?? 9? 1 14:30:18 2017
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = adder2
INCLUDEPATH += .

# Input
HEADERS += adder.h
SOURCES += adder.cpp testadder.cpp
