######################################################################
# Automatically generated by qmake (3.0) ?? 9? 2 09:54:45 2017
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = adder3
INCLUDEPATH += .

# Input
HEADERS += adder.h jfq.h MyLineEdit.h
SOURCES += adder.cpp main.cpp MyLineEdit.cpp
