######################################################################
# Automatically generated by qmake (3.0) ?? 9? 4 13:58:22 2017
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = SnakeGame
INCLUDEPATH += .

# Input
HEADERS += snakegame.h
SOURCES += main.cpp snakegame.cpp
