######################################################################
# Automatically generated by qmake (3.0) ?? 9? 1 17:06:17 2017
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = gettime
INCLUDEPATH += .

# Input
HEADERS += gettime.h
SOURCES += gettime.cpp testgettime.cpp
