######################################################################
# Automatically generated by qmake (3.0) ?? 9? 1 09:10:27 2017
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = qqlogin
INCLUDEPATH += .

# Input
SOURCES += qqlogin.cpp
