######################################################################
# Automatically generated by qmake (3.0) ?? 9? 1 21:15:17 2017
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = qqlogin3
INCLUDEPATH += .

# Input
HEADERS += myqqlogin.h qqlogin.h
FORMS += qqlogin.ui
SOURCES += myqqlogin.cpp testmain.cpp
