######################################################################
# Automatically generated by qmake (3.0) ?? 9? 1 15:00:28 2017
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = qqlogin2
INCLUDEPATH += .

# Input
HEADERS += qqlogin.h
SOURCES += main.cpp qqlogin.cpp
